import React from 'react';

import { NextPage } from 'next';
import Head from 'next/head';

const PageComponent: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">skrip.dev!</a>
        </h1>
      </main>
    </div>
  );
};

export default PageComponent;
